Use and instead of ampersand in description of firewalld service
The ampersand symbol (&) caused issues with firewalld:

```
ERROR: Failed to load service file
'/etc/firewalld/services/monitoring.xml': INVALID_SERVICE: not a valid
service file: not well-formed (invalid token): line 9, column 74
```

For the sake of simplicity I've replaced this symbol with "and".